src/Entity/Chambre.php
<?php

namespace App\Entity;

use App\Repository\ChambreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ChambreRepository::class)]
class Chambre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $numero = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $dateEntree = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $section = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $handicap = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $capacite_lit = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $batiment = null;

    #[ORM\Column(nullable: true)]
    private ?int $etage = null;

    /**
     * @var Collection<int, Etatlieux>
     */
    #[ORM\OneToMany(targetEntity: Etatlieux::class, mappedBy: 'chambre')]
    private Collection $etatslieux;

    #[ORM\Column]
    private ?bool $statut = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $soutirageEau = null;

    #[ORM\Column]
    private ?bool $amenagement = null;

    public function __construct()
    {
        $this->etatslieux = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumero(): ?int
    {
        return $this->numero;
    }

    public function setNumero(int $numero): static
    {
        $this->numero = $numero;

        return $this;
    }

    public function getDateEntree(): ?\DateTimeImmutable
    {
        return $this->dateEntree;
    }

    public function setDateEntree(?\DateTimeImmutable $dateEntree): static
    {
        $this->dateEntree = $dateEntree;

        return $this;
    }

    public function getSection(): ?string
    {
        return $this->section;
    }

    public function setSection(?string $section): static
    {
        $this->section = $section;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getHandicap(): ?string
    {
        return $this->handicap;
    }

    public function setHandicap(?string $handicap): static
    {
        $this->handicap = $handicap;

        return $this;
    }

    public function getCapaciteLit(): ?string
    {
        return $this->capacite_lit;
    }

    public function setCapaciteLit(?string $capacite_lit): static
    {
        $this->capacite_lit = $capacite_lit;

        return $this;
    }

    public function getBatiment(): ?string
    {
        return $this->batiment;
    }

    public function setBatiment(?string $batiment): static
    {
        $this->batiment = $batiment;

        return $this;
    }

    public function getEtage(): ?int
    {
        return $this->etage;
    }

    public function setEtage(?int $etage): static
    {
        $this->etage = $etage;

        return $this;
    }

    /**
     * @return Collection<int, Etatlieux>
     */
    public function getEtatslieux(): Collection
    {
        return $this->etatslieux;
    }

    public function addEtatslieux(Etatlieux $etatslieux): static
    {
        if (!$this->etatslieux->contains($etatslieux)) {
            $this->etatslieux->add($etatslieux);
            $etatslieux->setChambre($this);
        }

        return $this;
    }

    public function removeEtatslieux(Etatlieux $etatslieux): static
    {
        if ($this->etatslieux->removeElement($etatslieux)) {
            // set the owning side to null (unless already changed)
            if ($etatslieux->getChambre() === $this) {
                $etatslieux->setChambre(null);
            }
        }

        return $this;
    }

    public function isStatut(): ?bool
    {
        return $this->statut;
    }

    public function setStatut(bool $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    public function getSoutirageEau(): ?\DateTimeImmutable
    {
        return $this->soutirageEau;
    }

    public function setSoutirageEau(?\DateTimeImmutable $soutirageEau): static
    {
        $this->soutirageEau = $soutirageEau;

        return $this;
    }

    public function isAmenagement(): ?bool
    {
        return $this->amenagement;
    }

    public function setAmenagement(bool $amenagement): static
    {
        $this->amenagement = $amenagement;

        return $this;
    }
}

src/Form/ChambreType.php
<?php

namespace App\Form;

use App\Entity\Chambre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\Choice;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class ChambreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('numero')
            // ->add('dateEntree', null, [
            //     'widget' => 'single_text',
            // ])
            ->add('capacite_lit', ChoiceType::class, [
                'choices' => [
                    'Simple' => 1,
                    'Double' => 2,
                ],
            ])
            ->add('batiment', ChoiceType::class, [
                'choices' => [
                    'A' => 'A',
                    'B' => 'B',
                    'C' => 'C',
                ],
            ])
            ->add('etage', ChoiceType::class, [
                'choices' => [
                    '0' => 1,
                    '1' => 2,
                    '2' => 3,
                ],
            ])
        
            // ->add('statut', ChoiceType::class, [
            //     'choices' => [
            //         'Occupé' => true,
            //         'vide' => false,
            //     ],
            // ])
            // ->add('soutirageEau', DateType::class, [
            //     'widget' => 'single_text',
            //     'format' => 'yyyy-MM-dd',
            // ])
            ->add('amenagement', ChoiceType::class, [
                'choices' => [
                    'PMR' => true,
                    'vide' => false,
                ],
            ])
            ;
            

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Chambre::class,
        ]);
    }
}

src/Controller/ChambreController.php
<?php

namespace App\Controller;

use App\Entity\Chambre;
use App\Form\ChambreType;
use App\Form\ChambreOccupantType;
use App\Repository\ChambreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\Loader\Configurator\form;

#[Route('/chambre')]
class ChambreController extends AbstractController
{
    #[IsGranted('ROLE_UTILISATEUR')]
    #[Route('/', name: 'app_chambre_index', methods: ['GET'])]
    public function index(ChambreRepository $chambreRepository): Response
    {
        return $this->render('chambre/index.html.twig', [
            'chambres' => $chambreRepository->findBy([], ['numero' => 'ASC']),
        ]);
    }

    #[IsGranted('ROLE_UTILISATEUR')]
    #[Route('/export', name: 'app_chambre_indexexport', methods: ['GET'])]
    public function indexexport(ChambreRepository $chambreRepository): Response
    {
        return $this->render('chambre/indexexcel.html.twig', [
            'chambres' => $chambreRepository->findBy([], ['numero' => 'ASC']),
        ]);
    }

    #[IsGranted('ROLE_UTILISATEUR')]
    #[Route('/planchambre', name: 'app_chambre_planchambre', methods: ['GET'])]
    public function indexplanchambre(ChambreRepository $chambreRepository): Response
    {
        return $this->render('chambre/planchambre.html.twig', [
            'chambres' => $chambreRepository->findBy([]),
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/new', name: 'app_chambre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $chambre = new Chambre();
        $form = $this->createForm(ChambreType::class, $chambre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($chambre);
            $entityManager->flush();

            return $this->redirectToRoute('app_chambre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('chambre/new.html.twig', [
            'chambre' => $chambre,
            'form' => $form,
        ]);
    }
    #[IsGranted('ROLE_GESTIONNAIRE')]
    #[Route('/{id}', name: 'app_chambre_show', methods: ['GET'])]
    public function show(Chambre $chambre): Response
    {
        return $this->render('chambre/show.html.twig', [
            'chambre' => $chambre,
        ]);
    }
    #[IsGranted('ROLE_GESTIONNAIRE')]
    #[Route('/{id}/editchambre', name: 'app_chambre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Chambre $chambre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ChambreType::class, $chambre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_chambre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('chambre/editchambre.html.twig', [
            'chambre' => $chambre,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_GESTIONNAIRE')]
    #[Route('/{id}/editoccupant', name: 'app_chambre_occupant_edit', methods: ['GET', 'POST'])]
    public function editoccupant(Request $request, Chambre $chambre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ChambreOccupantType::class, $chambre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_chambre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('chambre/editoccupant.html.twig', [
            'chambre' => $chambre,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/{id}', name: 'app_chambre_delete', methods: ['POST'])]
    public function delete(Request $request, Chambre $chambre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$chambre->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($chambre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_chambre_index', [], Response::HTTP_SEE_OTHER);
    }
    #[IsGranted('ROLE_GESTIONNAIRE')]
    #[Route('/changeStatut/{id}', name: 'app_chambre_change_status', methods: ['POST'])]
    public function changeStatus(Request $request, Chambre $chambre, EntityManagerInterface $entityManager): Response
    {
            $statut = $chambre->isStatut();
            if ($statut==0) { $chambre-> setSoutirageEau(null);}
            $chambre->setStatut(!$statut);
            $entityManager->flush();

        // on redirige sur la page en cours
        return $this->redirect($request->headers->get('referer'));
    }

    #[IsGranted('ROLE_GESTIONNAIRE')]
    #[Route('/changeSoutirage/{id}', name: 'app_chambre_change_soutirage_eau', methods: ['POST'])]
    public function changeSoutirage(Request $request, Chambre $chambre, EntityManagerInterface $entityManager): Response
    {
            $dateSoutirage = new \DateTimeImmutable();
            $chambre->setSoutirageEau($dateSoutirage);
            $entityManager->flush();



            

        // on redirige sur la page en cours
        return $this->redirect($request->headers->get('referer'));
    }


}

templates/chambre/_caution.html.twig
<form method="post" action="{{ path('app_etatlieux_caution', {'id': edlh.id}) }}" onsubmit="return confirm('Voulez-vous changer le statut de la caution ?');" onsubmit="confirm('Vous allez changer le status de la caution')">
    <button class="btn btn-custom btn-primary me-1"  data-toggle='tooltip' data-placement='top' title='Retour chéque de caution'> {{ edlh.caution ? "Retenir" : "Restituer"}}
    </button>
</form>

templates/chambre/_change_soutirage_eau.html.twig
    <form method="post" action="{{ path('app_chambre_change_soutirage_eau', {'id': chambre.id}) }}"  onsubmit="return confirm('Vous allez actualiser la date du soutirage d\'eau')">
        <button class="btn btn-custom btn-primary me-1"  data-toggle='tooltip' data-placement='top' title='Changer la date du soutirage d eau {{ chambre.soutirageEau|date('d/m/Y') }}'> <i class="fa-solid fa-droplet"></i> {{ chambre.soutirageEau|date('d/m/Y') }}
        </button>
    </form>

templates/chambre/_change_status.html.twig
    <form method="post" action="{{ path('app_chambre_change_status', {'id': chambre.id}) }}" onsubmit="return confirm('Voulez-vous changer le statut de la chambre ?');" onsubmit="confirm('Vous allez changer le status de la chambre')">
        <button class="btn btn-custom btn-primary me-1"  data-toggle='tooltip' data-placement='top' title='Change le statut de la chambre n°{{chambre.numero}}'> <i class="fa-solid fa-person"></i> {{ chambre.statut ? "Vider" : "Occuper"}}
        </button>
    </form>

templates/chambre/_delete_form.html.twig
    <form method="post" action="{{ path('app_chambre_delete', {'id': chambre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ chambre.id) }}">
        <button class="btn btn-custom btn-primary">Supprimer</button>
    </form>

templates/chambre/_form_chambre.html.twig
{# {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_row(form.numero) }}
    {{ form_row(form.capacite_lit) }}
    {{ form_row(form.batiment) }}
    {{ form_row(form.etage) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }} #}
{{ form_start(form, {'attr': {'class': 'form-horizontal'} } ) }}
    <div class="text-center w-50 mx-auto">
                <div class="d-flex justify-content-between mb-1">
                {{ form_label(form.numero, null, {'label': 'Numéro:'}) }}
                {{ form_widget(form.numero, {'attr': {'class': 'form-control w-75'} }) }}
                </div>
                <div class="d-flex justify-content-between mb-1">
                {{ form_label(form.capacite_lit, null, {'label': 'Capacité du lit :'}) }}
                {{ form_widget(form.capacite_lit, {'attr': {'class': 'form-control w-75'} }) }}
                </div>
                <div class="d-flex justify-content-between mb-1">
                {{ form_label(form.batiment) }}
                {{ form_widget(form.batiment, {'attr': {'class': 'form-control w-75'} }) }}
                </div>
                <div class="d-flex justify-content-between mb-1">
                {{ form_label(form.etage) }}
                {{ form_widget(form.etage, {'attr': {'class': 'form-control w-75'} }) }}
                </div>
                {# <div class="d-flex justify-content-between mb-1">
                {{ form_label(form.statut) }}
                {{ form_widget(form.statut, {'attr': {'class': 'form-control w-75'}}) }}
                </div> #}
                {# <div class="d-flex justify-content-between mb-1">
                {{ form_label(form.soutirageEau) }}
                {{ form_widget(form.soutirageEau, {'attr': {'class': 'form-control w-75'}}) }}
                </div> #}
                <div class="d-flex justify-content-between mb-1">
                {{ form_label(form.amenagement) }}
                {{ form_widget(form.amenagement, {'attr': {'class': 'form-control w-75'} }) }}
                </div>
                <button class="btn btn-custom btn-primary">{{ button_label|default('Save') }}</button>
        </div>
{{ form_end(form) }}

templates/chambre/_form_occupant.html.twig
{# {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_row(form.dateEntree) }}
    {{ form_row(form.section) }}
    {{ form_row(form.nom) }}
    {{ form_row(form.prenom) }}
    {{ form_row(form.handicap) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }} #}








{{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
    <div class="text-center w-50 mx-auto">
                <div class="d-flex justify-content-between mb-1">
                {{ form_label(form.dateEntree, null, {'label': 'Date entrée:'}) }}
                {{ form_widget(form.dateEntree, {'attr': {'class': 'form-control w-75'}}) }}
                </div>
                <div class="d-flex justify-content-between mb-1">
                {{ form_label(form.section, null, {'label': 'Section :'}) }}
                {{ form_widget(form.section, {'attr': {'class': 'form-control w-75'}}) }}
                </div>
                <div class="d-flex justify-content-between mb-1">
                {{ form_label(form.nom) }}
                {{ form_widget(form.nom, {'attr': {'class': 'form-control w-75'}}) }}          
                </div>
                <div class="d-flex justify-content-between mb-1">
                {{ form_label(form.prenom) }}
                {{ form_widget(form.prenom, {'attr': {'class': 'form-control w-75'}}) }}
                </div>
                <div class="d-flex justify-content-between mb-1">
                {{ form_label(form.handicap) }}
                {{ form_widget(form.handicap, {'attr': {'class': 'form-control w-75'}}) }}
                </div>
                <button class="btn btn-custom btn-primary">{{ button_label|default('Save') }}</button>
            
        
        </div>
{{ form_end(form) }}

templates/chambre/editchambre.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Chambre{% endblock %}

{% block body %}
    <div>
            <h1 class="text-center">Modifier la Chambre</h1>

            <div  class="d-flex flex-column">
                
                    {{ include('chambre/_form_chambre.html.twig', {'button_label': 'mettre à jour'}) }}
                
                <div class="d-flex flex-column align-items-center">
                    <a href="{{ path('app_chambre_index') }}" class="btn btn-custom btn-secondary">Retour à la liste</a>
                
                {% if is_granted('ROLE_ADMIN') %}
                {{ include('chambre/_delete_form.html.twig') }}
                {% endif %}
                   
                </div>
                
            </div>
    </div>


{% endblock %}

templates/chambre/editoccupant.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Chambre occupant{% endblock %}

{% block body %}
<div>
        <h1 class="text-center">Mettre à jour l'occupant</h1>

        <div  class="d-flex flex-column">

                {{ include('chambre/_form_occupant.html.twig', {'button_label': 'Mettre à jour'}) }}

            <div class="d-flex flex-column align-items-center">

                <a href="{{ path('app_chambre_index') }}" class="btn btn-custom btn-secondary">Retour à la liste</a>
                {% if is_granted('ROLE_ADMIN') %}
                {{ include('chambre/_delete_form.html.twig') }}
                {% endif %}
            </div>
        </div>
</div>

{% endblock %}

templates/chambre/indexexcel.html.twig
{% extends 'base.html.twig' %}
    


    {% block title %}Liste chambres{% endblock %}

    {% block body %}


    <div class="mb-3 mt-4 p-2">
        <h1 class="row h-100 justify-content-center fw-bold">Liste des chambres</h1>  
        <button id="exportButton" class="btn btn-success">Export</button> 
        <table class="table table-bordered table-striped mt-3  table-hover"  data-toggle='tooltip' data-placement='top' title="Couleur rouge = soutirage d'eau à faire, vert=fait">
            <thead>
                <tr>
                    <th colspan="12" class="text-center">Liste recapitulative des chambres</th>
                </tr>
                <tr>
                    <th class="bg-primary text-white">Numero</th>
                    <th class="bg-primary text-white">Date d'entree</th>
                    <th class="bg-primary text-white">Section</th>
                    <th class="bg-primary text-white">Nom</th>
                    <th class="bg-primary text-white">Prenom</th>
                    <th class="bg-primary text-white">Handicap</th>
                    <th class="bg-primary text-white">Capacite lit</th>
                    <th class="bg-primary text-white">Batiment</th>
                    <th class="bg-primary text-white">Etage</th>
                    <th class="bg-primary text-white">Statut</th>
                    <th class="bg-primary text-white">Soutirage d'eau</th>
                    <th class="bg-primary text-white">Amenagement</th>
                </tr>
            </thead>
        <tbody>
        {% for chambre in chambres %}
            <tr 
            {% if date(chambre.soutirageEau) < date('today')|date_modify('-15 days') or (chambre.soutirageEau == null and chambre.statut==false) %}
                class='table-danger'
            {% else %}
                class='table-success'
            {% endif %}
            >
                <td>{{ chambre.numero }}</td>
                <td>{{ chambre.dateEntree ? chambre.dateEntree|date('d-m-Y') : '' }}</td>
                <td>{{ chambre.section ? chambre.section : "_______" }}</td>
                <td>{{ chambre.nom ? chambre.nom : "_______" }}</td>
                <td>{{ chambre.prenom ? chambre.prenom : "_______" }}</td>
                <td>{{ chambre.handicap ? chambre.handicap : "_______" }}</td>
                <td>{{ chambre.capaciteLit ? chambre.capaciteLit : "_______" }}</td>
                <td>{{ chambre.batiment ? chambre.batiment : "_______" }}</td>
                <td>{{ chambre.etage ? chambre.etage : "_______" }}</td>
                <td>{{ chambre.statut ? "Occupe" : "Vide" }}</td>
                <td>{{ chambre.soutirageEau ? chambre.soutirageEau|date('d-m-Y') : '' }}
                <td>{{ chambre.amenagement ? "PMR" : "" }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">Aucun enregistrement trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>

    {% endblock %}

templates/chambre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Chambre{% endblock %}

{% block body %}
    <h1>Create new Chambre</h1>

    {{ include('chambre/_form_chambre.html.twig') }}

    <a href="{{ path('app_chambre_index') }}">back to list</a>

{% endblock %}

templates/chambre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chambre{% endblock %}

{% block body %}
{# <pre>
    {{ dump(chambre.id) }}
</pre> #}
<div class="container my-5">
    <div class="row">
        <div class="col-12">

            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered mt-4  table-hover">
                        <tbody>
                            <h2 class="text-center">Descriptif chambre</h2>
                            <tr>
                                <th>Chambre :</th>
                                <td>{{ chambre.numero }}</td>
                            </tr>
                            <tr>
                                <th>Batiment</th>
                                <td>{{ chambre.batiment }}</td>
                            </tr>
                            <tr>
                                <th>Etage</th>
                                <td>{{ chambre.etage }}</td>
                            </tr>
                            <tr>
                                <th>Capacite_lit</th>
                                <td>{{ chambre.capaciteLit }}</td>
                            </tr>
                            
                            <tr>
                                <th>Statut :</th>
                                <td>{{ chambre.statut ? 'Occupé' : 'Vide' }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-md-6">
                    <table class="table table-bordered mt-4  table-hover">
                        <tbody>
                        <h2>Occupant :</h2>
                            <tr>
                                <th>DateEntree</th>
                                <td>{{ chambre.dateEntree ? chambre.dateEntree|date('Y-m-d H:i:s') : '' }}</td>
                            </tr>
                            <tr>
                                <th>Nom</th>
                                <td>{{ chambre.nom }}</td>
                            </tr>
                            <tr>
                                <th>Prenom</th>
                                <td>{{ chambre.prenom }}</td>
                            </tr>
                            <tr>
                                <th>Section</th>
                                <td>{{ chambre.section }}</td>
                            </tr>
                            <tr>
                                <th>Handicap</th>
                                <td>{{ chambre.handicap }}</td>
                            </tr>
                            <tr>
                                {# <th>Présent :</th>
                                <td>oui</td> #}
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="mt-3">
                {{ include('chambre/_change_status.html.twig') }}
         
                
                {% set test = false %}
                {% set id = null %}
                {% for edl in chambre.etatslieux %}
                    {% if (edl.isStatut == 0) %}
                        {% set test = true %}
                        {% set id = edl.id %}
                    {% endif %}
                {% endfor %}
                {% if (chambre.nom != null) and (chambre.prenom != null) and (chambre.section != null) and (chambre.dateEntree != null) %}
                    {% if test == false or chambre.etatslieux|length == 0 %}
                    <a href="{{ path('app_etatlieux_new', {'id': chambre.id}) }}" class="btn btn-warning"><i class="fas fa-plus"></i> créer état lieux</a>
                    {% else %}
                    <a href="{{ path('app_etatlieux_edit', {'id': id}) }}" class="btn btn-primary">Faire état sortie</a>
                    {% endif %}
                {% endif %}
                
            </div>
            <h2 class="mt-4">Historique :</h2>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th class="text-center">Nom</th>
                        <th class="w-25 text-center">Date d'entrée</th>
                        <th class="w-25 text-center">Date de sortie</th>
                        <th class="text-center">Statut</th>
                        <th></th>
                        <th class="w-25 text-center">Voir état des lieux</th>
                    </tr>
                </thead>
                <tbody>
            {% for edlh in chambre.etatslieux|slice(0,5) %}
            
            {% if edlh  %}
           
                    <tr>
                       <td class="p-3">{{ edlh.nom }}</td>
                       <td class="p-3">{{ edlh.dateEntree ? edlh.dateEntree|date('d-m-Y') : '' }}</td>
                       <td class="p-3">{{ edlh.dateSortie ? edlh.dateSortie|date('d-m-Y') : '' }}</td>
                       <td>{{ edlh.caution ? "Restituée" : "Retenue" }}</td>
                            
                       <td class="p-3"> {% if edlh.caution == 0 %}
                                {{include("chambre/_caution.html.twig")}} 
                            {% endif %}
                        </td>
                        <td class="p-3"><a class="btn bg-success d-flex justify-content-center text-white" href="{{ path('app_etatlieux_show', {'id': edlh.id}) }}">Voir</a></td>
                    </tr>
                
                
                
                    
                    {% endif %}
                    {% endfor %}
                </tbody>
          </table>
          
            <a href="{{ path('app_chambre_index') }}">Retour à la liste</a>

                    <a href="{{ path('app_chambre_edit', {'id': chambre.id}) }}" class="btn btn-warning btn-sm">Modifier la chambre</a>            
                    <a href="{{ path('app_chambre_occupant_edit', {'id': chambre.id}) }}" class="btn btn-warning btn-sm">Modifier l'occupant</a>
        </div>
    </div>
</div>


{{ include('chambre/_delete_form.html.twig') }}

{% endblock %}